import machineUrl from "./img/machine.png";
import leverUpUrl from "./img/lever_up.png";
import leverPressUrl from "./img/lever_press.png";

export const IMG = machineUrl;
export const UP_SPR = leverUpUrl;
export const PRESS_SPR = leverPressUrl;
export const COVER_SPR = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAE4AAAClCAYAAADyKctcAAABa0lEQVR4nO3QwQ3AIBDAsNL9dz5mIB+EZE8QZc3MfBz7bwe8yrjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLjIuMi4yLhoA8peBUZ6DKiuAAAAAElFTkSuQmCC";
